#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function

import sys
from fluggo.media.process import FFContainer

c = FFContainer(sys.argv[1])

print('Format: ', c.formatLongName, ' (', c.formatName, ')', sep='')

if c.mimeType:
	print('MIME type:', c.mimeType)

for stream in c.streams:
	print()
	print('Stream #', str(stream.index), ' (', stream.type, ')', sep='')
	print('Time base:', stream.timeBase)
	
	if stream.startTime:
		print('Start time:', stream.startTime)
	if stream.duration:
		print('Duration:', stream.duration)

	if stream.frameCount:
		print('Frames:', stream.frameCount)
	if stream.realFrameRate:
		print('Frame rate (guess):', stream.realFrameRate)
	if stream.encoding:
		print('Encoding:', stream.encoding)
	print('Codec:', stream.codec)
	
	if stream.bitRate:
		print('Bit rate:', stream.bitRate)
	
	if stream.type == 'video':
		print('Pixel format:', stream.pixelFormat)
		print('Frame size:', stream.frameSize)
	
		if stream.sampleAspectRatio:
			print('Sample aspect ratio:', stream.sampleAspectRatio)
	elif stream.type == 'audio':
		print('Sample rate:', stream.sampleRate, 'Hz')
		print('Channels:', stream.channels)

